// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.CanShallowClone(System.Linq.Expressions.Expression{System.Func{`0,System.Object}})~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.CanShallowClone(System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.Clone(System.Linq.Expressions.Expression{System.Func{`0,System.Object}})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.Clone(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.GetFields~System.Collections.Generic.IReadOnlyList{Deipax.Model.Interfaces.IFieldModelInfo}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.GetProperties~System.Collections.Generic.IReadOnlyList{Deipax.Model.Interfaces.IPropertyModelInfo}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.NoClone(System.Linq.Expressions.Expression{System.Func{`0,System.Object}})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.NoClone(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.ShallowClone(System.Linq.Expressions.Expression{System.Func{`0,System.Object}})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.CloneCmdConfig`1.ShallowClone(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.Cloner`1.Get(`0,Deipax.Cloning.Common.CopyContext)~`0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'Expression<CloneDel<T>> ExpressionHelper.Get<T>(CloneArgs args)', validate parameter 'args' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.Common.ExpressionHelper.Get``1(Deipax.Cloning.Common.CloneArgs)~System.Linq.Expressions.Expression{Deipax.Cloning.CloneDel{``0}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'bool FieldInfoExtensions.IsSupported(FieldInfo fieldInfo)', validate parameter 'fieldInfo' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.Extensions.FieldInfoExtensions.IsSupported(System.Reflection.FieldInfo)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'bool IFieldModelInfoExtensions.CanShallowClone(IFieldModelInfo source)', validate parameter 'source' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.Extensions.IFieldModelInfoExtensions.CanShallowClone(Deipax.Model.Interfaces.IFieldModelInfo)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'bool IPropertyModelInfoExtensions.CanShallowClone(IPropertyModelInfo source)', validate parameter 'source' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.Extensions.IPropertyModelInfoExtensions.CanShallowClone(Deipax.Model.Interfaces.IPropertyModelInfo)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'bool TypeExtensions.IsSupported(Type source)', validate parameter 'source' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Cloning.Extensions.TypeExtensions.IsSupported(System.Type)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:Deipax.Cloning.CloneCmdConfig`1.CloneCmd")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:Deipax.Cloning.CloneCmdConfig`1.ShallowCloneType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:Deipax.Cloning.CloneConfig`1.CloneDel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:Deipax.Cloning.CloneConfig`1.Initializer")]