// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'TValue QuickCache<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> factory)', validate parameter 'factory' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Core.Common.QuickCache`2.GetOrAdd(`0,System.Func{`0,`1})~`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'bool TypeExtensions.HasDefaultConstructor(Type t)', validate parameter 't' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Core.Extensions.TypeExtensions.HasDefaultConstructor(System.Type)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'bool TypeExtensions.IsAnonymous(Type type)', validate parameter 'type' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Core.Extensions.TypeExtensions.IsAnonymous(System.Type)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'bool TypeExtensions.IsNullable(Type source)', validate parameter 'source' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.Core.Extensions.TypeExtensions.IsNullable(System.Type)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2237:Add [Serializable] to DynamicDictionary as this type implements ISerializable", Justification = "<Pending>", Scope = "type", Target = "~T:Deipax.Core.Common.DynamicDictionary")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1710:Rename Deipax.Core.Common.DynamicRow to end in 'Dictionary'.", Justification = "<Pending>", Scope = "type", Target = "~T:Deipax.Core.Common.DynamicRow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2237:Add [Serializable] to QuickCache as this type implements ISerializable", Justification = "<Pending>", Scope = "type", Target = "~T:Deipax.Core.Common.QuickCache`2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1710:Rename Deipax.Core.Common.QuickCache<TKey, TValue> to end in 'Dictionary'.", Justification = "<Pending>", Scope = "type", Target = "~T:Deipax.Core.Common.QuickCache`2")]