// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.DataAccess.Common.DataRecordMap`1.Create(Deipax.DataAccess.Common.DataReaderCache)~System.Func{System.Data.IDataRecord,`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Task<DbCommand> IDbCmdExtensions.CreateAndOpenAsync(IDbCmd source)' passes a literal string as parameter 'message' of a call to 'InvalidOperationException.InvalidOperationException(string message)'. Retrieve the following string(s) from a resource table instead: \"Async operations require use of a DbCommand\".", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.DataAccess.Extensions.IDbCmdExtensions.CreateAndOpenAsync(Deipax.DataAccess.Interfaces.IDbCmd)~System.Threading.Tasks.Task{System.Data.Common.DbCommand}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Task<DbDataReader> IDbCommandExtensions.ExecuteReaderAsync(IDbCommand source, IDbCmd dbCmd)' passes a literal string as parameter 'message' of a call to 'InvalidOperationException.InvalidOperationException(string message)'. Retrieve the following string(s) from a resource table instead: \"Async operations require use of a DbConnection or an IDbConnection where .CreateCommand() returns a DbCommand\".", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.DataAccess.Extensions.IDbCommandExtensions.ExecuteReaderAsync(System.Data.IDbCommand,Deipax.DataAccess.Interfaces.IDbCmd)~System.Threading.Tasks.Task{System.Data.Common.DbDataReader}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Task<DbConnection> IDbConnectionExtensions.EnsureOpenAsync(IDbConnection source, CancellationToken? token = null)' passes a literal string as parameter 'message' of a call to 'InvalidOperationException.InvalidOperationException(string message)'. Retrieve the following string(s) from a resource table instead: \"Async operations require use of a DbConnection or an already-open IDbConnection\".", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.DataAccess.Extensions.IDbConnectionExtensions.EnsureOpenAsync(System.Data.IDbConnection,System.Nullable{System.Threading.CancellationToken})~System.Threading.Tasks.Task{System.Data.Common.DbConnection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1720:Identifier 'Single' contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.DataAccess.Extensions.IDbConnectionExtensions.Single(System.Data.IDbConnection,System.String,System.Data.IDbDataParameter[],System.Data.IDbTransaction,System.Nullable{System.Int32},System.Nullable{System.Data.CommandType})~")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1720:Identifier 'Single' contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:Deipax.DataAccess.Extensions.IDbConnectionExtensions.Single``1(System.Data.IDbConnection,System.String,System.Data.IDbDataParameter[],System.Data.IDbTransaction,System.Nullable{System.Int32},System.Nullable{System.Data.CommandType})~``0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1710:Rename Deipax.DataAccess.Concretes.ManagedEnumerable to end in 'Collection'.", Justification = "<Pending>", Scope = "type", Target = "~T:Deipax.DataAccess.Concretes.ManagedEnumerable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1710:Rename Deipax.DataAccess.Concretes.ManagedEnumerable<T> to end in 'Collection'.", Justification = "<Pending>", Scope = "type", Target = "~T:Deipax.DataAccess.Concretes.ManagedEnumerable`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1710:Rename Deipax.DataAccess.Interfaces.IManagedEnumerable<T> to end in 'Collection'.", Justification = "<Pending>", Scope = "type", Target = "~T:Deipax.DataAccess.Interfaces.IManagedEnumerable`1")]